import type { GeneratedSurveyDraft } from './types';

/**
 * Few-Shot 用の良質なアンケート例。
 * geminiGenerator.ts のダイナミックプロンプトに埋め込み、生成品質の基準を示す。
 * Phase 2 以降は SurveyAI Lab の勝者 JSON で順次更新する。
 */
export const FEW_SHOT_EXAMPLES: GeneratedSurveyDraft[] = [
  {
    title: '大学生の睡眠習慣に関する調査',
    description: '大学生の睡眠の質・量と日常生活への影響を調べるアンケートです。',
    questions: [
      {
        type: 'single',
        text: '平日の平均的な就寝時刻を教えてください。',
        description: null,
        required: true,
        options: ['22時以前', '22〜23時', '23〜24時', '0〜1時', '1時以降'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'single',
        text: '平日の平均的な睡眠時間はどのくらいですか？',
        description: null,
        required: true,
        options: ['5時間未満', '5〜6時間', '6〜7時間', '7〜8時間', '8時間以上'],
        config: null,
        signal_meta: {
          role: 'consistency_anchor',
          pairKey: 'sleep-duration',
          positiveOptions: ['7〜8時間', '8時間以上'],
        },
      },
      {
        type: 'single',
        text: '朝、すっきり目覚めることができていますか？',
        description: '毎日の目覚めの質を全体的に評価してください。',
        required: true,
        options: ['毎日すっきり目覚める', 'だいたいすっきり目覚める', 'あまり目覚めが良くない', 'ほぼ毎日つらい'],
        config: null,
        signal_meta: {
          role: 'consistency_check',
          pairKey: 'sleep-duration',
          contradictsWith: ['ほぼ毎日つらい'],
        },
      },
      {
        type: 'single',
        text: '就寝前1時間以内にスマートフォンを使用しますか？',
        description: null,
        required: true,
        options: ['ほぼ毎日使用する', '週に3〜5回', '週に1〜2回', 'ほとんど使用しない'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'attention',
        text: '以下の選択肢の中から「赤」を選んでください。',
        description: '設問を注意深く読んでお答えください。',
        required: true,
        options: ['青', '赤', '緑', '黄'],
        config: { correctOptionText: '赤' },
        signal_meta: { role: 'attention_check' },
      },
      {
        type: 'single',
        text: '睡眠の質が低いと感じたとき、翌日の学業・生活にどの程度影響しますか？',
        description: null,
        required: true,
        options: ['非常に影響する', 'ある程度影響する', 'あまり影響しない', 'まったく影響しない'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'single',
        text: '睡眠改善のために現在取り組んでいることはありますか？',
        description: null,
        required: true,
        options: ['積極的に取り組んでいる', '少し取り組んでいる', '取り組もうと思っているが実践できていない', '特に取り組んでいない'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'paragraph',
        text: '睡眠に関して困っていることや改善したいことがあれば自由にお書きください。',
        description: null,
        required: false,
        options: [],
        config: null,
        signal_meta: { role: 'open_signal' },
      },
    ],
  },
  {
    title: '就職活動に関する意識調査',
    description: '大学生・大学院生の就職活動への取り組み姿勢や不安を把握するための調査です。',
    questions: [
      {
        type: 'single',
        text: '現在の学年を教えてください。',
        description: null,
        required: true,
        options: ['学部2年生以下', '学部3年生', '学部4年生', '大学院1年生', '大学院2年生以上'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'single',
        text: '就職活動を始めましたか（インターンシップ参加・説明会参加・ES提出などを含む）？',
        description: null,
        required: true,
        options: ['すでに内定・内々定がある', '選考中・活動中', '準備はしているがまだ始めていない', '全く始めていない'],
        config: null,
        signal_meta: {
          role: 'consistency_anchor',
          pairKey: 'job-hunting-status',
          positiveOptions: ['すでに内定・内々定がある', '選考中・活動中'],
        },
      },
      {
        type: 'multiple',
        text: '就職活動で力を入れている（または入れる予定の）活動を選んでください（複数選択可）。',
        description: null,
        required: true,
        options: ['インターンシップ参加', '会社説明会・OB/OG訪問', 'ES・履歴書作成', '面接対策', '自己分析', 'Webテスト対策', 'まだ何もしていない'],
        config: null,
        signal_meta: {
          role: 'consistency_check',
          pairKey: 'job-hunting-status',
          contradictsWith: ['まだ何もしていない'],
        },
      },
      {
        type: 'single',
        text: '就職活動に対してどの程度不安を感じていますか？',
        description: null,
        required: true,
        options: ['非常に不安', 'やや不安', 'あまり不安ではない', '全く不安ではない'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'attention',
        text: '選択肢の中から「就職活動」を選んでください。',
        description: '設問をよく読んでお答えください。',
        required: true,
        options: ['アルバイト', '就職活動', 'サークル活動', '学業'],
        config: { correctOptionText: '就職活動' },
        signal_meta: { role: 'attention_check' },
      },
      {
        type: 'single',
        text: '志望業界は決まっていますか？',
        description: null,
        required: true,
        options: ['業界・職種ともにほぼ決まっている', '業界はある程度絞れている', 'いくつか候補はあるが迷っている', 'まだ全く決まっていない'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'single',
        text: '就職活動情報の収集に最も役立っているのはどれですか？',
        description: null,
        required: true,
        options: ['就活サイト（マイナビ・リクナビ等）', 'SNS・口コミサイト', '大学のキャリアセンター', 'OB/OG・社会人の知人', 'その他'],
        config: null,
        signal_meta: { role: 'standard' },
      },
      {
        type: 'paragraph',
        text: '就職活動で最も大変だと感じること、または不安なことを自由にお書きください。',
        description: null,
        required: false,
        options: [],
        config: null,
        signal_meta: { role: 'open_signal' },
      },
    ],
  },
];
